load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "remote-query",
    srcs = [
        "executor.go",
        "recordset.go",
        "server.go",
    ],
    importpath = "github.com/pingcap/tidb/util/serverless/remote-query",
    visibility = ["//visibility:public"],
    deps = [
        "//metrics",
        "//parser/ast",
        "//parser/auth",
        "//parser/model",
        "//sessionctx/variable",
        "//types",
        "//util/chunk",
        "//util/logutil",
        "//util/serverless/tidbworker",
        "//util/sqlexec",
        "@com_github_google_uuid//:uuid",
        "@com_github_gorilla_mux//:mux",
        "@org_uber_go_zap//:zap",
    ],
)
